export const colorsList = [
  { hex: '#000000', name: 'Negro' },
  { hex: '#ffffff', name: 'Blanco' },
  { hex: '#808080', name: 'Gris' },
  { hex: '#c0c0c0', name: 'Plata' },
  { hex: '#c1121f', name: 'Rojo' },
  { hex: '#1d4ed8', name: 'Azul' },
  { hex: '#6b4226', name: 'Café' },
  { hex: '#d9c6a5', name: 'Beige' },
  { hex: '#166534', name: 'Verde' },
  { hex: '#f59e0b', name: 'Amarillo' },
  { hex: '#ea580c', name: 'Naranja' },
  { hex: '#b8860b', name: 'Dorado' },
  { hex: '#7b1e2b', name: 'Vino' },
]
